name: example
description: An example showing how the rebloc library works.

dependencies:
  flutter:
    sdk: flutter
  rebloc:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.7.0
  test: ^1.6.3

environment:
  sdk: '>=2.4.0 <3.0.0'

flutter:
  uses-material-design: true
