name: example
description: An example showing how the rebloc library works.

dependencies:

  rebloc:
    path: ../
  intl: ^0.15.7

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

