name: listexample
description: An example showing how rebloc can minimize list rebuilds.

dependencies:
  rebloc:
    path: ../
  intl: ^0.15.8
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.6.3
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.4.0 <3.0.0'

flutter:
  uses-material-design: true
