name: listexample
description: An example showing how rebloc can minimize list rebuilds.

dependencies:

  rebloc:
    path: ../
  intl: ^0.15.7

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
