name: rebloc
description: A new flutter package project.
version: 0.0.1
author: Andrew Brogdon <brogdon+github@gmail.com>
homepage: https://github.com/redbrogdon/rebloc

dependencies:

  rxdart: ^0.18.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
